openapi: 3.0.0
info:
  title: Credit Card Issuer API
  description: API for managing credit card accounts and retrieving account information
  version: 1.0.0
  contact:
    name: API Support
    email: support@cardissuer.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development server

paths:
  /credit-cards/{accountId}:
    get:
      summary: Get credit card account details
      description: Retrieve detailed information about a specific credit card account
      operationId: getCreditCardAccount
      tags:
        - Credit Cards
      parameters:
        - name: accountId
          in: path
          required: true
          description: Credit card account identifier
          schema:
            type: string
            pattern: '^00[0-9]{13}$'
            example: "001234567890123"
      responses:
        '200':
          description: Credit card account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardAccount'
        '404':
          description: Credit card account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreditCardAccount:
      type: object
      description: Credit card account information including balance, rewards, and payment details
      required:
        - accountId
        - totalBalance
        - membershipRewardPoints
        - paymentDueDate
      example:
        account_id: "001234567890123"
        total_balance: 1250.75
        membership_reward_points: 15420
        payment_due_date: "2025-08-15"
      properties:
        # VIOLATION: These should be camelCase, not snake_case
        account_id:
          type: string
          description: Credit card account identifier
          example: "001234567890123"
        total_balance:
          type: number
          format: float
          minimum: 0
          description: Current total balance on the account in USD
          example: 1250.75
        membership_reward_points:
          type: integer
          minimum: 0
          description: Available membership reward points
          example: 15420
        payment_due_date:
          type: string
          format: date
          description: Next payment due date in ISO 8601 format
          example: "2025-08-15"

    ErrorResponse:
      type: object
      description: Standard error response format for API errors
      required:
        - error
        - message
      example:
        error: "Not Found"
        message: "Credit card account not found"
      properties:
        error:
          type: string
          description: Error type
          example: "Not Found"
        message:
          type: string
          description: Human-readable error message
          example: "Credit card account not found"

tags:
  - name: Credit Cards
    description: Operations related to credit card accounts
