openapi: 3.0.0
info:
  title: Credit Card Issuer API
  description: API for managing credit card accounts and retrieving account information
  version: 1.0.0
  contact:
    name: API Support
    email: support@cardissuer.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.cardissuer.com
    description: Production server

paths:
  /credit-cards/{accountId}:
    get:
      summary: Get credit card account details
      description: Retrieve detailed information about a specific credit card account including balance, reward points, and payment due date
      operationId: getCreditCardAccount
      tags:
        - Credit Cards
      parameters:
        - name: accountId
          in: path
          required: true
          description: Credit card account identifier (15 digits starting with 00)
          schema:
            type: string
            pattern: '^00[0-9]{13}$'
            example: "001234567890123"
      responses:
        '200':
          description: Credit card account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCardAccount'
              examples:
                example1:
                  summary: Sample credit card account
                  value:
                    accountId: "001234567890123"
                    totalBalance: 1250.75
                    minimumDue: 37.52
                    membershipRewardPoints: 15420
                    paymentDueDate: "2025-08-15"
        '404':
          description: Credit card account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                notFound:
                  summary: Account not found
                  value:
                    error: "Not Found"
                    message: "Credit card account not found"
        '400':
          description: Invalid account ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check endpoint
      description: Check if the API service is running and healthy
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    CreditCardAccount:
      type: object
      description: Credit card account information including balance, rewards, and payment details
      required:
        - accountId
        - totalBalance
        - minimumDue
        - membershipRewardPoints
        - paymentDueDate
      example:
        accountId: "001234567890123"
        totalBalance: 1250.75
        minimumDue: 37.52
        membershipRewardPoints: 15420
        paymentDueDate: "2025-08-15"
      properties:
        accountId:
          type: string
          description: Credit card account identifier (15 digits starting with 00)
          pattern: '^00[0-9]{13}$'
          example: "001234567890123"
        totalBalance:
          type: number
          format: float
          minimum: 0
          description: Current total balance on the account in USD
          example: 1250.75
        minimumDue:
          type: number
          format: float
          minimum: 0
          description: Minimum payment amount due by the payment due date
          example: 37.52
        membershipRewardPoints:
          type: integer
          minimum: 0
          description: Available membership reward points
          example: 15420
        paymentDueDate:
          type: string
          format: date
          description: Next payment due date in ISO 8601 format (YYYY-MM-DD)
          example: "2025-08-15"

    ErrorResponse:
      type: object
      description: Standard error response format for API errors
      required:
        - error
        - message
      example:
        error: "Not Found"
        message: "Credit card account not found"
      properties:
        error:
          type: string
          description: Error type
          example: "Not Found"
        message:
          type: string
          description: Human-readable error message
          example: "Credit card account not found"

    HealthResponse:
      type: object
      description: Health check response indicating service status
      required:
        - status
        - timestamp
      example:
        status: "healthy"
        timestamp: "2025-07-14T10:30:00.000Z"
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          description: Current health status of the service
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Timestamp when health check was performed
          example: "2025-07-14T10:30:00.000Z"

tags:
  - name: Credit Cards
    description: Operations related to credit card accounts
  - name: Health
    description: Service health and monitoring endpoints
