name: API Quality Gates

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  spectral-lint:
    name: Spectral API Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Spectral API Linting
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: 'openapi.yaml'
          spectral_ruleset: '.spectral.yml'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
